# Site settings
title: George Nunes Generalist Developer
description: Portfolio and contact information of George Nunes Generalist Developer
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: George Nunes
user_description: Gamer, technophile, perfeccionist, self-taught, curious and enthusiast of computing, logic, algorithms, puzzles and challenges. At late mid school, when internet connection was dial up, I first met mIRC. After trying several 3rd party customizations of it, decided to create my own and learnt it's scripting language to do it. When it was done, had to learn HTML to publish it. With mid school about to end and determined to dive in the area, applied and pass in Fundação Matias Machline's (former Fundação Nokia de Ensino) exam to study computing along with high school and become a technician. Later went to college at Universidade do Estado do Amazonas (UEA) and graduate in Computer Engineering. Then started working as Android app developer at Samsung Technology Institute (SIDIA) and further made part of Black River Studios' engineering team.
user_title: Generalist Developer
email: georgedarocha@gmail.com
twitter_username: georgedarocha
github_username: georgedarocha
facebook_username: georgedarocha
linkedin_username: georgedarocha

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
